export const myProjects = [
    {
        id: 1,
        type: "front-end",
        title: "Ecommerce Next.js",
        shortDescription: "E-commerce platform with product browsing, shopping cart, wishlist, authentication, and a fully responsive user experience.",
        fullDescription: "Developed a full-stack e-commerce application using Next.js and TypeScript, delivering a fast and scalable shopping experience. The project includes product listing and filtering, detailed product pages, shopping cart management, wishlist functionality, user authentication, and responsive layouts for all devices. Built with React and Tailwind CSS to ensure maintainable code, reusable components, and a modern user interface while leveraging Next.js features for performance optimization and routing.",
        technologies: ["Next.js", "TypeScript", "React", "Tailwind CSS"],
        githubUrl: "https://github.com/Eslam-mg/Ecommerce-Next.tsx",
        liveUrl: "https://ecommerce-next-tsx.vercel.app/",
        mainImage: "/projects/ecommerce/main_img.webp",
        videoUrl: "/projects/ecommerce/video.mp4",
        images: [
            "/projects/ecommerce/main_img.webp",
            "/projects/ecommerce/products.webp",
            "/projects/ecommerce/product-details.webp",
            "/projects/ecommerce/cartList.webp",
            "/projects/ecommerce/wishlist.webp",
            "/projects/ecommerce/login.webp",
            "/projects/ecommerce/singup.webp"
        ],
    },
    {
        id: 2,
        type:"data analysis",
        title: "Supply Chain Dashboard",
        shortDescription: "Interactive dashboard providing insights into sales performance, inventory management, supplier efficiency, and key supply chain metrics.",
        fullDescription: "Designed and developed a Supply Chain Analytics Dashboard to transform raw business data into actionable insights. The dashboard analyzes sales trends, inventory levels, supplier performance, shipping operations, and key operational KPIs. Data was cleaned, transformed, and modeled using SQL, Python, and Power Query before being visualized in Power BI. Interactive reports and drill-down features enable stakeholders to monitor performance, identify bottlenecks, and support data-driven decision making.",
        technologies: ["Python", "SQL", "Power Query", "Power BI"],
        githubUrl: "https://github.com/Eslam-mg/Data-Analysis-Learning/tree/main/supply%20chain",
        liveUrl: "",
        mainImage: "/projects/supply chain/main_img.webp",
        videoUrl: "/projects/supply chain/video.mp4",
        images: [
            "/projects/supply chain/main_img.webp",
            "/projects/supply chain/customersTooltip.webp",
            "/projects/supply chain/customers.webp",
            "/projects/supply chain/sales.webp",
            "/projects/supply chain/shipping.webp"
        ],
    },
    {
        id: 3,
        type:"front-end",
        title: "Masihe",
        shortDescription: "Advertisement platform that allows users to publish, browse, and manage ads through an intuitive and responsive interface.",
        fullDescription: "Masihe is a responsive advertisement platform developed with React, designed to connect users through a seamless ad publishing and browsing experience. The platform includes user authentication, profile management, category-based ad organization, and detailed advertisement pages. Users can explore listings, view advertiser profiles, and navigate content efficiently through a clean and user-friendly interface. The project focuses on reusable components, responsive design, performance optimization, and modern front-end development best practices",
        technologies: ["React", "JavaScript", "React-Cookie", "Formik", "Yup"],
        githubUrl: "https://github.com/Eslam-mg/Romoz_Tec",
        liveUrl: "",
        mainImage: "/projects/masihe/main_img.webp",
        videoUrl: "/projects/masihe/video.mp4",
        images: [
            "/projects/masihe/main_img.webp",
            "/projects/masihe/detailes-ad.webp",
            "/projects/masihe/login.webp",
            "/projects/masihe/register.webp",
            "/projects/masihe/ShowAnyUser.webp",
            "/projects/masihe/SpecificCategory.webp",
            "/projects/masihe/UserProfile.webp",
        ],
    },
    {
        id: 4,
        type:"data analysis",
        title: "Customer Booking",
        shortDescription: "Interactive dashboard that analyzes airline customer booking data, providing insights into booking behavior, flight preferences.",
        fullDescription: "Customer Booking is a data analysis project built in Excel to explore and visualize airline booking data through an interactive dashboard. The project focuses on transforming raw booking data into meaningful insights using data cleaning, pivot tables, charts, and KPI tracking. Users can analyze booking trends, customer preferences, route performance, and overall business metrics through a clear and easy-to-navigate dashboard. The project demonstrates practical data analysis skills, data visualization techniques, and the ability to support data-driven decision-making using Microsoft Excel.",
        technologies: ["Excel"],
        githubUrl: "https://github.com/Eslam-mg/Airline-Booking-Data-Analysis-Dashboard-Excel-Project",
        liveUrl: "",
        mainImage: "/projects/customer_booking/main_img.webp",
        videoUrl: "/projects/customer_booking/video.mp4",
        images: [
            "/projects/customer_booking/main_img.webp",
            "/projects/customer_booking/map.webp",
        ],
    },
    {
        id: 5,
        type:"front-end",
        title: "Suadi Made",
        shortDescription: "Modern platform showcasing Saudi-made products with a responsive design, authentication system, and seamless user experience.",
        fullDescription: "Saudi Made is a modern e-commerce web application developed to promote and showcase locally manufactured Saudi products. The platform provides users with a smooth browsing experience through a responsive and intuitive interface, allowing them to explore products, manage their accounts, and interact with the platform efficiently. The project includes user authentication, profile management, product browsing, and optimized navigation. Built with modern front-end technologies, the application emphasizes clean architecture, reusable components, performance optimization, and mobile-friendly design principles.",
        technologies: ["React", "Vite", "TypeScript", "Tailwind Css", ""],
        githubUrl: "https://github.com/Eslam-mg/suadi-made",
        liveUrl: "https://suadi-made.vercel.app/",
        mainImage: "/projects/suadi-made/main_img.webp",
        videoUrl: "/projects/suadi-made/video.mp4",
        images: [
            "/projects/suadi-made/main_img.webp",
            "/projects/suadi-made/company.webp",
            "/projects/suadi-made/home.webp",
            "/projects/suadi-made/login.webp",
            "/projects/suadi-made/user.webp",
        ],
    },
    {
        id: 6,
        type:"front-end",
        title: "Recipe",
        shortDescription: "Responsive web allows users to explore meals from different countries, view detailed recipes, ingredients and cooking instructions.",
        fullDescription: "Recipe is a modern web application that allows users to explore a wide variety of meals from different countries through a clean and responsive interface. Users can browse meals by country, view detailed information about each meal, including ingredients, preparation instructions, and images. The application integrates with an external API to fetch real-time recipe data and provides smooth navigation with a mobile-friendly design. Built with React, Axios, JavaScript, Sass, and AOS, the project focuses on reusable components, API integration, responsive layouts, and delivering an intuitive user experience.",
        technologies: ["React", "Axios", "JavaScript", "Sass", "Aos"],
        githubUrl: "https://github.com/Eslam-mg/Recipe_Route",
        liveUrl: "https://recipe-pi-seven.vercel.app/",
        mainImage: "/projects/recipe/main_img.webp",
        videoUrl: "/projects/recipe/video.mp4",
        images: [
            "/projects/recipe/main_img.webp",
            "/projects/recipe/company.webp",
            "/projects/recipe/home.webp",
            "/projects/recipe/login.webp",
            "/projects/recipe/user.webp",
        ],
    },
];