export const myProjects = [
    {
        id: 1,
        type: "front-end",
        title: "Ecommerce Next.js",
        shortDescription: "E-commerce platform with product browsing, shopping cart, wishlist, authentication, and a fully responsive user experience.",
        fullDescription: "Developed a full-stack e-commerce application using Next.js and TypeScript, delivering a fast and scalable shopping experience. The project includes product listing and filtering, detailed product pages, shopping cart management, wishlist functionality, user authentication, and responsive layouts for all devices. Built with React and Tailwind CSS to ensure maintainable code, reusable components, and a modern user interface while leveraging Next.js features for performance optimization and routing.",
        technologies: ["Next.js", "TypeScript", "React", "Tailwind CSS"],
        githubUrl: "https://github.com/Eslam-mg/Ecommerce-Next.tsx",
        liveUrl: "https://ecommerce-next-tsx.vercel.app/",
        mainImage: "/projects/ecommerce/main_img.webp",
        videoUrl: "/projects/ecommerce/video.mp4",
        images: [
            "/projects/ecommerce/main_img.webp",
            "/projects/ecommerce/products.webp",
            "/projects/ecommerce/product-details.webp",
            "/projects/ecommerce/cartList.webp",
            "/projects/ecommerce/wishlist.webp",
            "/projects/ecommerce/login.webp",
            "/projects/ecommerce/singup.webp"
        ],
    },
    {
        id: 2,
        type:"data analysis",
        title: "Supply Chain Dashboard",
        shortDescription: "Interactive dashboard providing insights into sales performance, inventory management, supplier efficiency, and key supply chain metrics.",
        fullDescription: "Designed and developed a Supply Chain Analytics Dashboard to transform raw business data into actionable insights. The dashboard analyzes sales trends, inventory levels, supplier performance, shipping operations, and key operational KPIs. Data was cleaned, transformed, and modeled using SQL, Python, and Power Query before being visualized in Power BI. Interactive reports and drill-down features enable stakeholders to monitor performance, identify bottlenecks, and support data-driven decision making.",
        technologies: ["Python", "SQL", "Power Query", "Power BI"],
        githubUrl: "https://github.com/Eslam-mg/Data-Analysis-Learning/tree/main/supply%20chain",
        liveUrl: "",
        mainImage: "/projects/supply chain/main_img.webp",
        videoUrl: "/projects/supply chain/video.mp4",
        images: [
            "/projects/supply chain/main_img.webp",
            "/projects/supply chain/customersTooltip.webp",
            "/projects/supply chain/customers.webp",
            "/projects/supply chain/sales.webp",
            "/projects/supply chain/shipping.webp"
        ],
    },
    {
        id: 3,
        type:"front-end",
        title: "Masihe",
        shortDescription: "Advertisement platform that allows users to publish, browse, and manage ads through an intuitive and responsive interface.",
        fullDescription: "Masihe is a responsive advertisement platform developed with React, designed to connect users through a seamless ad publishing and browsing experience. The platform includes user authentication, profile management, category-based ad organization, and detailed advertisement pages. Users can explore listings, view advertiser profiles, and navigate content efficiently through a clean and user-friendly interface. The project focuses on reusable components, responsive design, performance optimization, and modern front-end development best practices",
        technologies: ["React", "JavaScript", "React-Cookie", "Formik", "Yup"],
        githubUrl: "https://github.com/Eslam-mg/Romoz_Tec",
        liveUrl: "",
        mainImage: "/projects/masihe/main_img.webp",
        videoUrl: "/projects/masihe/video.mp4",
        images: [
            "/projects/masihe/main_img.webp",
            "/projects/masihe/detailes-ad.webp",
            "/projects/masihe/login.webp",
            "/projects/masihe/register.webp",
            "/projects/masihe/ShowAnyUser.webp",
            "/projects/masihe/SpecificCategory.webp",
            "/projects/masihe/UserProfile.webp",
        ],
    },
];